[package]
name = "datafusion-sharp-native"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.43"
datafusion = "52.1.0"
flatbuffers = "25.12.19"
futures = "0.3.31"
tokio = { version = "1.49.0", features = ["rt-multi-thread"] }
