[package]
name = "datafusion-sharp-native"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "unwind"
debug = 1
lto = "thin"

[profile.dev]
panic = "unwind"

[dependencies]
anyhow = "1.0.101"
chrono = "0.4.43"
arrow-array = { version = "57.3.0", features = ["ffi"] }
datafusion = "52.1.0"
datafusion-proto = "52.1.0"
futures = "0.3.31"
prost = "0.14.3"
tokio = { version = "1.49.0", features = ["rt-multi-thread"] }

[build-dependencies]
prost-build = "0.14.3"
